<?php

declare(strict_types=1);

namespace Asids\Core\Identity\Domain\Events;

use Asids\Core\Identity\Domain\Models\User;
use Illuminate\Foundation\Events\Dispatchable;
use Illuminate\Queue\SerializesModels;

/**
 * A user was invited to a workspace.
 *
 * The signed URL is carried on the event rather than regenerated by the listener, so the
 * link that reaches the mailbox is provably the one that was signed — regenerating would
 * silently issue a second link with a later expiry.
 */
final class UserInvited
{
    use Dispatchable;
    use SerializesModels;

    public function __construct(
        public readonly User $user,
        public readonly User $invitedBy,
        public readonly string $invitationUrl,
    ) {}
}
