<?php

declare(strict_types=1);

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

/**
 * Immutable, tamper-evident audit trail.
 *
 * Three properties make this suitable for a system of financial record:
 *
 *   1. Append only. A database trigger rejects every UPDATE and every DELETE, so
 *      no application bug — and no compromised application credential — can
 *      rewrite history. Retention pruning is the single exception and must
 *      announce itself through a session variable that only the schema owner can
 *      set.
 *
 *   2. Hash chained. Each row stores the SHA-256 of its own canonical payload
 *      concatenated with the previous row's hash, per tenant. Removing or
 *      altering any row breaks every subsequent link, which the
 *      `asids:audit-verify` command detects.
 *
 *   3. Self-describing. Old and new values, the actor, the impersonator (if any),
 *      the request that caused it and the resulting hash are all in one row, so
 *      an auditor never needs to correlate across systems.
 */
return new class extends Migration
{
    public function up(): void
    {
        Schema::create('audit_logs', function (Blueprint $table): void {
            $table->uuid('id')->primary();

            // Globally monotonic insertion order. The hash chain is ordered by
            // this column within a tenant. It is a PostgreSQL identity column
            // rather than a second primary key: `id` stays the surrogate key that
            // application code and API responses use.
            $table->bigInteger('sequence');

            $table->uuid('tenant_id')->nullable();
            $table->uuid('company_id')->nullable();

            // ── What changed ───────────────────────────────────────────────
            $table->string('auditable_type');
            $table->uuid('auditable_id');
            $table->string('event', 32);
            $table->jsonb('old_values')->nullable();
            $table->jsonb('new_values')->nullable();
            $table->jsonb('changed_attributes')->nullable();

            // ── Who did it ─────────────────────────────────────────────────
            $table->string('actor_type', 24)->default('user');
            $table->uuid('actor_id')->nullable();
            $table->string('actor_label')->nullable();
            // Set when an ASIDS operator was acting as the user.
            $table->uuid('impersonator_id')->nullable();
            $table->uuid('access_token_id')->nullable();

            // ── In what context ────────────────────────────────────────────
            $table->string('ip_address', 45)->nullable();
            $table->text('user_agent')->nullable();
            $table->string('request_method', 10)->nullable();
            $table->text('request_url')->nullable();
            $table->uuid('request_id')->nullable();
            $table->string('channel', 24)->default('web');
            $table->jsonb('tags')->nullable();
            $table->text('reason')->nullable();

            // ── Integrity ──────────────────────────────────────────────────
            $table->char('previous_hash', 64)->nullable();
            $table->char('hash', 64);

            $table->timestampTz('created_at')->useCurrent();

            // The chain walk, and the per-tenant timeline view.
            $table->index(['tenant_id', 'sequence']);
            $table->index(['tenant_id', 'created_at']);
            // "History of this record" — the most common auditor question.
            $table->index(['auditable_type', 'auditable_id', 'sequence'], 'audit_logs_auditable_index');
            $table->index(['actor_id', 'created_at']);
            $table->index(['tenant_id', 'company_id', 'created_at']);
            $table->index('request_id');
        });

        // Let PostgreSQL own the sequence so no two writers can pick the same
        // ordinal, and make it unique so a gap or a duplicate is impossible.
        DB::statement('ALTER TABLE audit_logs ALTER COLUMN sequence ADD GENERATED BY DEFAULT AS IDENTITY');
        DB::statement('ALTER TABLE audit_logs ADD CONSTRAINT audit_logs_sequence_unique UNIQUE (sequence)');

        DB::statement("ALTER TABLE audit_logs ADD CONSTRAINT audit_logs_event_check CHECK (event IN ('created', 'updated', 'deleted', 'restored', 'force_deleted', 'viewed', 'exported', 'approved', 'rejected', 'posted', 'voided', 'login', 'logout', 'permission_changed', 'setting_changed', 'impersonation_started', 'impersonation_ended'))");
        DB::statement("ALTER TABLE audit_logs ADD CONSTRAINT audit_logs_actor_type_check CHECK (actor_type IN ('user', 'system', 'api_token', 'console', 'job'))");
        DB::statement("ALTER TABLE audit_logs ADD CONSTRAINT audit_logs_channel_check CHECK (channel IN ('web', 'api', 'mobile', 'console', 'queue'))");
        // A system actor has no identity; a user actor must have one.
        DB::statement("ALTER TABLE audit_logs ADD CONSTRAINT audit_logs_actor_identity_check CHECK (actor_type <> 'user' OR actor_id IS NOT NULL)");

        // GIN indexes let an auditor ask "which change touched this field?" and
        // "which entries carry this tag?" without scanning the table.
        DB::statement('CREATE INDEX audit_logs_new_values_gin ON audit_logs USING gin (new_values jsonb_path_ops)');
        DB::statement('CREATE INDEX audit_logs_tags_gin ON audit_logs USING gin (tags jsonb_path_ops)');

        // ── Append-only enforcement ────────────────────────────────────────
        DB::statement(<<<'SQL'
            CREATE OR REPLACE FUNCTION asids_audit_logs_guard() RETURNS trigger
            LANGUAGE plpgsql
            AS $$
            BEGIN
                IF TG_OP = 'UPDATE' THEN
                    RAISE EXCEPTION 'audit_logs is append-only; UPDATE is not permitted (id=%)', OLD.id
                        USING ERRCODE = 'restrict_violation';
                END IF;

                IF TG_OP = 'DELETE' THEN
                    -- Retention pruning is the only legitimate deletion. The
                    -- pruning job announces itself, and the row must be older
                    -- than the retention horizon it declares.
                    IF COALESCE(current_setting('asids.audit_prune', true), 'off') <> 'on' THEN
                        RAISE EXCEPTION 'audit_logs is append-only; DELETE is not permitted (id=%)', OLD.id
                            USING ERRCODE = 'restrict_violation';
                    END IF;
                END IF;

                RETURN OLD;
            END;
            $$;
        SQL);

        DB::statement(<<<'SQL'
            CREATE TRIGGER audit_logs_guard
                BEFORE UPDATE OR DELETE ON audit_logs
                FOR EACH ROW EXECUTE FUNCTION asids_audit_logs_guard();
        SQL);

        // TRUNCATE bypasses row triggers entirely, so it is blocked separately.
        DB::statement(<<<'SQL'
            CREATE OR REPLACE FUNCTION asids_audit_logs_truncate_guard() RETURNS trigger
            LANGUAGE plpgsql
            AS $$
            BEGIN
                RAISE EXCEPTION 'audit_logs may not be truncated'
                    USING ERRCODE = 'restrict_violation';
            END;
            $$;
        SQL);

        DB::statement(<<<'SQL'
            CREATE TRIGGER audit_logs_truncate_guard
                BEFORE TRUNCATE ON audit_logs
                FOR EACH STATEMENT EXECUTE FUNCTION asids_audit_logs_truncate_guard();
        SQL);

        DB::statement('COMMENT ON TABLE audit_logs IS \'Append-only, hash-chained audit trail. See asids:audit-verify.\'');
    }

    public function down(): void
    {
        // The guards must go before the table, or the drop itself is refused in
        // a way that is confusing to debug.
        DB::statement('DROP TRIGGER IF EXISTS audit_logs_truncate_guard ON audit_logs');
        DB::statement('DROP TRIGGER IF EXISTS audit_logs_guard ON audit_logs');
        Schema::dropIfExists('audit_logs');
        DB::statement('DROP FUNCTION IF EXISTS asids_audit_logs_truncate_guard()');
        DB::statement('DROP FUNCTION IF EXISTS asids_audit_logs_guard()');
    }
};
